pipeline {
    agent { label 'AGENT-1' }
    options {
        timeout(time:30, unit:'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices:['apply', 'destroy'], description:'Select Action')
    }
    stages {
        stage('Init and Plan') {
            steps {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                    sh """
                        cd 60-alb
                        terraform init -upgrade
                        terraform plan -out=tfplan || true
                    """
                }
            }
        }
        stage('Apply or Destroy') {
            steps {
                withAWS(region:'us-east-1', credentials:'aws-creds') {
                    sh """
                        cd 60-alb
                        terraform init -reconfigure
                        if [ "${params.ACTION}" == "apply" ]; then
                            terraform apply -auto-approve tfplan
                        elif [ "${params.ACTION}" == "destroy" ]; then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
    }
    post {
        always {
            echo "This section runs always"
            deleteDir()
        }
    }
}
