pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices: ['apply','destroy'], description: 'select Action') 
    }
    stages {
        stage('init and plan') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """
                        cd 40-eks
                        terraform init -upgrade
                        terraform plan -out=tfplan
                """
                }
            }
        }
        stage('Apply or Destroy') {
            steps {
                withAWS(region: 'us-east-1', credentials: 'aws-cred') {
                    sh """
                        cd 40-eks
                        if [ "${params.ACTION}" == "apply" ]; then
                            terraform apply -auto-aprove
                        elif [ "${params.ACTION}" == "destroy"]; then
                            terraform destroy -auto-approve
                        fi
                    """

                }
            }
        }
    }
    post {
        always {
            echo "This section runs always"
            deleteDir()
        }
    }
}