pipeline {
    agent {
        label 'AGENT-1'
    }
    options {
        timeout(time: 30, unit: 'MINUTES')
        disableConcurrentBuilds()
        ansiColor('xterm')
    }
    parameters {
        choice(name: 'ACTION', choices:['apply','destroy'], description: 'select Action' )
    }
    stages {
        stage('init and plan') {
            steps{
                withAWS(region: 'us-east-1', credentials: 'aws-creds') {
                    sh """ 
                        cd 10-sg
                        terraform init -upgrade
                        terraform plan -out=tfplan
                    """
                }
            }
        }
        stage('Apply or Destroy') {
            steps {
                withAWS(region: 'us-east-1', credentials:'aws-creds') {
                    sh """
                        cd 10-sg
                        if [ "${params.ACTION}" == "apply" ]; then
                            terraform apply -auto-approve tfplan
                        elif [ "${params.ACTION}" == "destroy" ]; then
                            terraform destroy -auto-approve
                        fi
                    """
                }
            }
        }
        stage('Destroy VPC') {
            when {
                expression { params.ACTION == 'destroy'}
            }
            steps {
                build job: '00-vpc', parameters: [string(name: 'ACTION', value: 'destroy')], wait: false
            }
        }
        stage('Parallel') {
            when {
                expression { params.ACTION == 'apply' }
            }
            parallel {
                stage('Bastion') {
                    steps {
                        build job: '20-bastion', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
                stage('EKS') {
                    steps {
                        build job: '40-eks', parameters: [string(name: 'ACTION', value: 'apply')], wait: false
                    }
                }
            }
        }
    }
    
    post {
        always {
            echo "This section run always"
            deleteDir()
        }
    }
}